import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ContextProviders from "@/context/ContextProviders";
import ThemeWrapper from "@/components/ui/theme/ThemeWrapper";
import Topbar from "@/components/ui/topbar/Topbar";
import { Pacifico } from "next/font/google";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

const pacifico = Pacifico({
    subsets: ["latin"],
    weight: "400",
    display: "swap",
    variable: "--font-pacifico",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <ContextProviders>
                    <ThemeWrapper>
                        <div className={`${pacifico.variable} ${geistSans.variable} ${geistMono.variable} antialiased h-screen`}>
                            <div className="py-10 flex flex-col items-center justify-start gap-y-6">

                                <Topbar />
                                {children}
                            </div>
                        </div>
                    </ThemeWrapper>
                </ContextProviders>
            </body>
        </html >
    );
}
